"""auto

Revision ID: 6c19a958a641
Revises: a16d45db5335
Create Date: 2025-12-05 20:47:21.129767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c19a958a641'
down_revision: Union[str, Sequence[str], None] = 'a16d45db5335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_plate_number'), table_name='message')
    op.create_index(op.f('ix_message_plate_number'), 'message', ['plate_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_plate_number'), table_name='message')
    op.create_index(op.f('ix_message_plate_number'), 'message', ['plate_number'], unique=1)
    # ### end Alembic commands ###
