"""create message loaded table

Revision ID: bd12a13f16d6
Revises: 6d3a0113cf3e
Create Date: 2025-12-01 21:25:27.229443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd12a13f16d6'
down_revision: Union[str, Sequence[str], None] = '6d3a0113cf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_loaded',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_loaded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_loaded_id'), 'message_loaded', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_loaded_id'), table_name='message_loaded')
    op.drop_table('message_loaded')
    # ### end Alembic commands ###
